# Generated by Django 3.0.2 on 2020-02-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userBio', models.CharField(max_length=200)),
                ('userPic', models.FileField(blank=True, upload_to='')),
                ('ip_addr', models.GenericIPAddressField()),
                ('content_type', models.CharField(max_length=50)),
            ],
        ),
    ]
