# Generated by Django 3.0.2 on 2020-02-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_auto_20200217_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ip_addr',
        ),
    ]
