# Generated by Django 3.0.2 on 2020-02-20 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_remove_profile_ip_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_input_text',
        ),
    ]
