# Generated by Django 3.0.2 on 2020-02-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_auto_20200219_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userPic',
            new_name='profile_picture',
        ),
    ]
