# Generated by Django 3.0.2 on 2020-02-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_auto_20200220_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='user_picture',
        ),
    ]
