# Generated by Django 3.0.2 on 2020-02-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_auto_20200220_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_picture',
            new_name='profile_picture',
        ),
    ]
