# Generated by Django 3.0.2 on 2020-02-27 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0008_auto_20200220_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('post_id', models.CharField(default=None, max_length=200)),
                ('user_id', models.CharField(default=None, max_length=200)),
                ('user_profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='socialnetwork.Profile')),
            ],
        ),
    ]
