# Generated by Django 3.0.2 on 2020-02-28 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0011_comment_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='poster',
        ),
    ]
