# Generated by Django 3.0.2 on 2020-02-28 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialnetwork', '0012_remove_comment_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='poster_of_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
