# Generated by Django 3.0.2 on 2020-02-28 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0013_comment_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='poster_of_comment', to='socialnetwork.Profile'),
        ),
    ]
