# Generated by Django 3.0.2 on 2020-02-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0019_auto_20200228_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_count_id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
