# Generated by Django 3.0.2 on 2020-02-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0020_comment_post_count_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_count_id',
            new_name='post_ref',
        ),
    ]
