# Generated by Django 3.0.2 on 2020-02-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0021_auto_20200228_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_user_id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
