# Generated by Django 3.0.2 on 2020-02-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0022_post_poster_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
