# Generated by Django 3.0.2 on 2020-02-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0023_post_poster_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date_time',
            field=models.DateTimeField(),
        ),
    ]
